using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IBVD.Digital.Logic.Helper
{
    public static class ConfigurationWellKnowKeys
    {
        public static string DIRECTORIO_IMAGENES_ROOT = "DIRECTORIO.IMAGENES.ROOT";

        public static string IMAGEN_MINIATURA = "IMAGEN.MINIATURA";

        public static string IMAGEN_ANCHO_MAX = "IMAGEN.ANCHO.MAX";

        public static string IMAGEN_NO_ENCONTRADA = "IMAGEN.NO.ENCONTRADA";

        public static string REUNION_CANCIONES_MAX = "REUNION.CANCIONES.MAXIMA.DURACION";

        public static string CANCION_FORMAT_DATA_BASICO = "CANCION.FORMAT.DATA.BASICO";

        public static string DIRECTORIO_BIBLIAS = "DIRECTORIO.BIBLIAS.ROOT";

        public static string DIRECTORIO_IMAGENES_PERFIL = "DIRECTORIO.IMAGENES.PERFIL";

        public static string DIRECTORIO_MAIL_TEMPLATES = "DIRECTORIO.MAIL.TEMPLATES";

        public static string DIRECTORIO_MAIL_TEMPLATE_BASE = "DIRECTORIO.MAIL.TEMPLATE.BASE";

        public static string DIRECTORIO_MAIL_TEMPLATE_REGISTRACION_EMAIL = "DIRECTORIO.MAIL.TEMPLATE.REGISTRACION.EMAIL";
        
        public static string DIRECTORIO_MAIL_TEMPLATE_RECUPERACION_PASSWORD = "DIRECTORIO.MAIL.TEMPLATE.RECUPERACION.PASSWORD";
      
        public static string DIRECTORIO_MAIL_TEMPLATE_REUNION_MODIFICACION = "DIRECTORIO.MAIL.TEMPLATE.REUNION.MODIFICACION";

        public static string DIRECTORIO_MAIL_TEMPLATE_REUNION_CANCELACION = "DIRECTORIO.MAIL.TEMPLATE.REUNION.CANCELACION";

        public static string DIRECTORIO_MAIL_TEMPLATE_INFORMATIVO_LINK = "DIRECTORIO.MAIL.TEMPLATE.INFORMATIVO.LINK";

        public static string DIRECTORIO_MAIL_TEMPLATE_ACTUALIZACION_ENCARGADOS = "DIRECTORIO.MAIL.TEMPLATE.ACTUALIZACION.ENCARGADOS";
        public static string DIRECTORIO_MAIL_TEMPLATE_ACTUALIZACION_ENCARGADOS_ITEM = "DIRECTORIO.MAIL.TEMPLATE.ACTUALIZACION.ENCARGADOS.ITEM";

        public static string SITE_ROOT = "SITE.ROOT";
    }
}
